### PR TITLE
Flesh out the documentation for the core lifecycle annotations

### PR DESCRIPTION
**Pull request by eheimburg**
No code changes -- just some documentation tweaks. The lifecycle document is a good start, but I still had questions about how each annotation worked, and documenting the annotations seems like the best place to put more info. (It's where I looked first, anyway.)

I tried to only use examples that could be potentially useful -- for example, I didn't add examples of @PostPersist functions that take zero parameters, because I couldn't think of any situation where that would be useful.

This is just a draft -- open to alterations.

### CODE REVIEW

**Comment by evanchooly** [comment]
Thank you for taking the time for the updates.  You'll notice some failures on the CI run.  If you could clean those up, once we get a clean run we can merge.

**Review by evanchooly — CHANGES_REQUESTED** [review]
changes mentioned in the comments

**Comment by evanchooly** [comment]
> Thank you for taking the time for the updates. You'll notice some failures on the CI run. If you could clean those up, once we get a clean run we can merge.

mostly, these change can be made by running `mvn spotless:apply` in `core`.

**Comment by eheimburg** [comment]
also added a missing use-case from @PrePersist. I still didn't mention that it can take a Document parameter -- I can't think of a use-case for it, so treating as an undocumented implementation detail

**Comment by evanchooly** [comment]
Looks good!  Thanks for the patch.

**Pull request merged**
