### PR TITLE
bugfix: the resolve function would be called multiple times

### PR DESCRIPTION
**Pull request by danielBreitlauch**
Small fix such that resolved is set to true.

### CODE REVIEW

**Comment by evanchooly** [comment]
I think I see what's going on here but a bug description and tests would be really helpful.

**Comment by danielBreitlauch** [comment]
It is just a performance regression. By adding the break; there 'resolved = true;' is never called. So the routine is not cached and executed every time.

**Comment by danielBreitlauch** [comment]
@evanchooly do you consider this fix of the previously introduces performance regression?

**Comment by danielBreitlauch** [comment]
Ping?

**Pull request merged**
