### PR TITLE
check index of parameters is not out of bounds

### PR DESCRIPTION
**Pull request by daniel-exceed**
in parameterized types there can be an exception of IndexOutOfBounds due to not limiting the peek index while looping on it.
I've fixed it here

### CODE REVIEW

**Comment by evanchooly** [comment]
This code is years old without any index boundary issues.  I would like to see a test verifying this is an actual issue before applying any fix.  Generally speaking, PRs without tests won't get merged.

**Comment by daniel-exceed** [comment]
@evanchooly 
I used the reproducer project and managed to reproduce it here:
https://github.com/daniel-exceed/entity-model-builder-index-out-of-bounds

**Comment by daniel-exceed** [comment]
@evanchooly i opened an issue to document this:
https://github.com/MorphiaOrg/morphia/issues/2197

**Comment by evanchooly** [comment]
Thanks for the PR.  I apologize for taking so long to merge. There's been a fair bit of stuff going on on my end.  I manually merged this one because there were some tweaks needed to the test.  Take a look at the final form and follow that test set up for your other PR.

**Pull request closed without merging**
